// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file api/v1/ipam.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcquireChildPrefixRequest, AcquireChildPrefixResponse, AcquireIPRequest, AcquireIPResponse, CreateNamespaceRequest, CreateNamespaceResponse, CreatePrefixRequest, CreatePrefixResponse, DeleteNamespaceRequest, DeleteNamespaceResponse, DeletePrefixRequest, DeletePrefixResponse, DumpRequest, DumpResponse, GetPrefixRequest, GetPrefixResponse, ListNamespacesRequest, ListNamespacesResponse, ListPrefixesRequest, ListPrefixesResponse, LoadRequest, LoadResponse, PrefixUsageRequest, PrefixUsageResponse, ReleaseChildPrefixRequest, ReleaseChildPrefixResponse, ReleaseIPRequest, ReleaseIPResponse } from "./ipam_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.IpamService
 */
export const IpamService = {
  typeName: "api.v1.IpamService",
  methods: {
    /**
     * @generated from rpc api.v1.IpamService.CreatePrefix
     */
    createPrefix: {
      name: "CreatePrefix",
      I: CreatePrefixRequest,
      O: CreatePrefixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.DeletePrefix
     */
    deletePrefix: {
      name: "DeletePrefix",
      I: DeletePrefixRequest,
      O: DeletePrefixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.GetPrefix
     */
    getPrefix: {
      name: "GetPrefix",
      I: GetPrefixRequest,
      O: GetPrefixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.ListPrefixes
     */
    listPrefixes: {
      name: "ListPrefixes",
      I: ListPrefixesRequest,
      O: ListPrefixesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.PrefixUsage
     */
    prefixUsage: {
      name: "PrefixUsage",
      I: PrefixUsageRequest,
      O: PrefixUsageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.AcquireChildPrefix
     */
    acquireChildPrefix: {
      name: "AcquireChildPrefix",
      I: AcquireChildPrefixRequest,
      O: AcquireChildPrefixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.ReleaseChildPrefix
     */
    releaseChildPrefix: {
      name: "ReleaseChildPrefix",
      I: ReleaseChildPrefixRequest,
      O: ReleaseChildPrefixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.AcquireIP
     */
    acquireIP: {
      name: "AcquireIP",
      I: AcquireIPRequest,
      O: AcquireIPResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.ReleaseIP
     */
    releaseIP: {
      name: "ReleaseIP",
      I: ReleaseIPRequest,
      O: ReleaseIPResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.Dump
     */
    dump: {
      name: "Dump",
      I: DumpRequest,
      O: DumpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.Load
     */
    load: {
      name: "Load",
      I: LoadRequest,
      O: LoadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.CreateNamespace
     */
    createNamespace: {
      name: "CreateNamespace",
      I: CreateNamespaceRequest,
      O: CreateNamespaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.ListNamespaces
     */
    listNamespaces: {
      name: "ListNamespaces",
      I: ListNamespacesRequest,
      O: ListNamespacesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.IpamService.DeleteNamespace
     */
    deleteNamespace: {
      name: "DeleteNamespace",
      I: DeleteNamespaceRequest,
      O: DeleteNamespaceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

