// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/ipam.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	ParentCidr    string                 `protobuf:"bytes,2,opt,name=parent_cidr,json=parentCidr,proto3" json:"parent_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prefix) Reset() {
	*x = Prefix{}
	mi := &file_api_v1_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefix) ProtoMessage() {}

func (x *Prefix) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefix.ProtoReflect.Descriptor instead.
func (*Prefix) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{0}
}

func (x *Prefix) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Prefix) GetParentCidr() string {
	if x != nil {
		return x.ParentCidr
	}
	return ""
}

type CreatePrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Prefix                `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrefixResponse) Reset() {
	*x = CreatePrefixResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrefixResponse) ProtoMessage() {}

func (x *CreatePrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrefixResponse.ProtoReflect.Descriptor instead.
func (*CreatePrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrefixResponse) GetPrefix() *Prefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type DeletePrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Prefix                `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrefixResponse) Reset() {
	*x = DeletePrefixResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrefixResponse) ProtoMessage() {}

func (x *DeletePrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrefixResponse.ProtoReflect.Descriptor instead.
func (*DeletePrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePrefixResponse) GetPrefix() *Prefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type GetPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Prefix                `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixResponse) Reset() {
	*x = GetPrefixResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixResponse) ProtoMessage() {}

func (x *GetPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixResponse.ProtoReflect.Descriptor instead.
func (*GetPrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{3}
}

func (x *GetPrefixResponse) GetPrefix() *Prefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type AcquireChildPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Prefix                `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireChildPrefixResponse) Reset() {
	*x = AcquireChildPrefixResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireChildPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireChildPrefixResponse) ProtoMessage() {}

func (x *AcquireChildPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireChildPrefixResponse.ProtoReflect.Descriptor instead.
func (*AcquireChildPrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireChildPrefixResponse) GetPrefix() *Prefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type ReleaseChildPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Prefix                `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseChildPrefixResponse) Reset() {
	*x = ReleaseChildPrefixResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseChildPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseChildPrefixResponse) ProtoMessage() {}

func (x *ReleaseChildPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseChildPrefixResponse.ProtoReflect.Descriptor instead.
func (*ReleaseChildPrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseChildPrefixResponse) GetPrefix() *Prefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type CreatePrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrefixRequest) Reset() {
	*x = CreatePrefixRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrefixRequest) ProtoMessage() {}

func (x *CreatePrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrefixRequest.ProtoReflect.Descriptor instead.
func (*CreatePrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePrefixRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CreatePrefixRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type DeletePrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrefixRequest) Reset() {
	*x = DeletePrefixRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrefixRequest) ProtoMessage() {}

func (x *DeletePrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrefixRequest.ProtoReflect.Descriptor instead.
func (*DeletePrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePrefixRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *DeletePrefixRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type GetPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixRequest) Reset() {
	*x = GetPrefixRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixRequest) ProtoMessage() {}

func (x *GetPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixRequest.ProtoReflect.Descriptor instead.
func (*GetPrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrefixRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *GetPrefixRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ListPrefixesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefixesRequest) Reset() {
	*x = ListPrefixesRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefixesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefixesRequest) ProtoMessage() {}

func (x *ListPrefixesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefixesRequest.ProtoReflect.Descriptor instead.
func (*ListPrefixesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{9}
}

func (x *ListPrefixesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ListPrefixesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []*Prefix              `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefixesResponse) Reset() {
	*x = ListPrefixesResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefixesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefixesResponse) ProtoMessage() {}

func (x *ListPrefixesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefixesResponse.ProtoReflect.Descriptor instead.
func (*ListPrefixesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{10}
}

func (x *ListPrefixesResponse) GetPrefixes() []*Prefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type PrefixUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixUsageRequest) Reset() {
	*x = PrefixUsageRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixUsageRequest) ProtoMessage() {}

func (x *PrefixUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixUsageRequest.ProtoReflect.Descriptor instead.
func (*PrefixUsageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{11}
}

func (x *PrefixUsageRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *PrefixUsageRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type PrefixUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AvailableIPs the number of available IPs if this is not a parent prefix
	// No more than 2^31 available IPs are reported
	AvailableIps uint64 `protobuf:"varint,1,opt,name=available_ips,json=availableIps,proto3" json:"available_ips,omitempty"`
	// AcquiredIPs the number of acquired IPs if this is not a parent prefix
	AcquiredIps uint64 `protobuf:"varint,2,opt,name=acquired_ips,json=acquiredIps,proto3" json:"acquired_ips,omitempty"`
	// AvailableSmallestPrefixes is the count of available Prefixes with 2 countable Bits
	// No more than 2^31 available Prefixes are reported
	AvailableSmallestPrefixes uint64 `protobuf:"varint,3,opt,name=available_smallest_prefixes,json=availableSmallestPrefixes,proto3" json:"available_smallest_prefixes,omitempty"`
	// AvailablePrefixes is a list of prefixes which are available
	AvailablePrefixes []string `protobuf:"bytes,4,rep,name=available_prefixes,json=availablePrefixes,proto3" json:"available_prefixes,omitempty"`
	// AcquiredPrefixes the number of acquired prefixes if this is a parent prefix
	AcquiredPrefixes uint64 `protobuf:"varint,5,opt,name=acquired_prefixes,json=acquiredPrefixes,proto3" json:"acquired_prefixes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrefixUsageResponse) Reset() {
	*x = PrefixUsageResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixUsageResponse) ProtoMessage() {}

func (x *PrefixUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixUsageResponse.ProtoReflect.Descriptor instead.
func (*PrefixUsageResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{12}
}

func (x *PrefixUsageResponse) GetAvailableIps() uint64 {
	if x != nil {
		return x.AvailableIps
	}
	return 0
}

func (x *PrefixUsageResponse) GetAcquiredIps() uint64 {
	if x != nil {
		return x.AcquiredIps
	}
	return 0
}

func (x *PrefixUsageResponse) GetAvailableSmallestPrefixes() uint64 {
	if x != nil {
		return x.AvailableSmallestPrefixes
	}
	return 0
}

func (x *PrefixUsageResponse) GetAvailablePrefixes() []string {
	if x != nil {
		return x.AvailablePrefixes
	}
	return nil
}

func (x *PrefixUsageResponse) GetAcquiredPrefixes() uint64 {
	if x != nil {
		return x.AcquiredPrefixes
	}
	return 0
}

type AcquireChildPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Length        uint32                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ChildCidr     *string                `protobuf:"bytes,3,opt,name=child_cidr,json=childCidr,proto3,oneof" json:"child_cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,4,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireChildPrefixRequest) Reset() {
	*x = AcquireChildPrefixRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireChildPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireChildPrefixRequest) ProtoMessage() {}

func (x *AcquireChildPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireChildPrefixRequest.ProtoReflect.Descriptor instead.
func (*AcquireChildPrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{13}
}

func (x *AcquireChildPrefixRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *AcquireChildPrefixRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *AcquireChildPrefixRequest) GetChildCidr() string {
	if x != nil && x.ChildCidr != nil {
		return *x.ChildCidr
	}
	return ""
}

func (x *AcquireChildPrefixRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ReleaseChildPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseChildPrefixRequest) Reset() {
	*x = ReleaseChildPrefixRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseChildPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseChildPrefixRequest) ProtoMessage() {}

func (x *ReleaseChildPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseChildPrefixRequest.ProtoReflect.Descriptor instead.
func (*ReleaseChildPrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{14}
}

func (x *ReleaseChildPrefixRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *ReleaseChildPrefixRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type IP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	ParentPrefix  string                 `protobuf:"bytes,2,opt,name=parent_prefix,json=parentPrefix,proto3" json:"parent_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_api_v1_ipam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{15}
}

func (x *IP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IP) GetParentPrefix() string {
	if x != nil {
		return x.ParentPrefix
	}
	return ""
}

type AcquireIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *IP                    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireIPResponse) Reset() {
	*x = AcquireIPResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireIPResponse) ProtoMessage() {}

func (x *AcquireIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireIPResponse.ProtoReflect.Descriptor instead.
func (*AcquireIPResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{16}
}

func (x *AcquireIPResponse) GetIp() *IP {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *AcquireIPResponse) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ReleaseIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *IP                    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPResponse) Reset() {
	*x = ReleaseIPResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPResponse) ProtoMessage() {}

func (x *ReleaseIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPResponse.ProtoReflect.Descriptor instead.
func (*ReleaseIPResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseIPResponse) GetIp() *IP {
	if x != nil {
		return x.Ip
	}
	return nil
}

type AcquireIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixCidr    string                 `protobuf:"bytes,1,opt,name=prefix_cidr,json=prefixCidr,proto3" json:"prefix_cidr,omitempty"`
	Ip            *string                `protobuf:"bytes,2,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireIPRequest) Reset() {
	*x = AcquireIPRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireIPRequest) ProtoMessage() {}

func (x *AcquireIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireIPRequest.ProtoReflect.Descriptor instead.
func (*AcquireIPRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{18}
}

func (x *AcquireIPRequest) GetPrefixCidr() string {
	if x != nil {
		return x.PrefixCidr
	}
	return ""
}

func (x *AcquireIPRequest) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *AcquireIPRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ReleaseIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixCidr    string                 `protobuf:"bytes,1,opt,name=prefix_cidr,json=prefixCidr,proto3" json:"prefix_cidr,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{19}
}

func (x *ReleaseIPRequest) GetPrefixCidr() string {
	if x != nil {
		return x.PrefixCidr
	}
	return ""
}

func (x *ReleaseIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ReleaseIPRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type DumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpRequest) Reset() {
	*x = DumpRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpRequest) ProtoMessage() {}

func (x *DumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpRequest.ProtoReflect.Descriptor instead.
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{20}
}

func (x *DumpRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type DumpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dump          string                 `protobuf:"bytes,1,opt,name=dump,proto3" json:"dump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpResponse) Reset() {
	*x = DumpResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpResponse) ProtoMessage() {}

func (x *DumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpResponse.ProtoReflect.Descriptor instead.
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{21}
}

func (x *DumpResponse) GetDump() string {
	if x != nil {
		return x.Dump
	}
	return ""
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dump          string                 `protobuf:"bytes,1,opt,name=dump,proto3" json:"dump,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{22}
}

func (x *LoadRequest) GetDump() string {
	if x != nil {
		return x.Dump
	}
	return ""
}

func (x *LoadRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{23}
}

type CreateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{24}
}

func (x *CreateNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{25}
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{26}
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     []string               `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{27}
}

func (x *ListNamespacesResponse) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type DeleteNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{29}
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{30}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	GitSha1       string                 `protobuf:"bytes,3,opt,name=git_sha1,json=gitSha1,proto3" json:"git_sha1,omitempty"`
	BuildDate     string                 `protobuf:"bytes,4,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{31}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *VersionResponse) GetGitSha1() string {
	if x != nil {
		return x.GitSha1
	}
	return ""
}

func (x *VersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

var File_api_v1_ipam_proto protoreflect.FileDescriptor

const file_api_v1_ipam_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/ipam.proto\x12\x06api.v1\"=\n" +
	"\x06Prefix\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x1f\n" +
	"\vparent_cidr\x18\x02 \x01(\tR\n" +
	"parentCidr\">\n" +
	"\x14CreatePrefixResponse\x12&\n" +
	"\x06prefix\x18\x01 \x01(\v2\x0e.api.v1.PrefixR\x06prefix\">\n" +
	"\x14DeletePrefixResponse\x12&\n" +
	"\x06prefix\x18\x01 \x01(\v2\x0e.api.v1.PrefixR\x06prefix\";\n" +
	"\x11GetPrefixResponse\x12&\n" +
	"\x06prefix\x18\x01 \x01(\v2\x0e.api.v1.PrefixR\x06prefix\"D\n" +
	"\x1aAcquireChildPrefixResponse\x12&\n" +
	"\x06prefix\x18\x01 \x01(\v2\x0e.api.v1.PrefixR\x06prefix\"D\n" +
	"\x1aReleaseChildPrefixResponse\x12&\n" +
	"\x06prefix\x18\x01 \x01(\v2\x0e.api.v1.PrefixR\x06prefix\"Z\n" +
	"\x13CreatePrefixRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"Z\n" +
	"\x13DeletePrefixRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"W\n" +
	"\x10GetPrefixRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"F\n" +
	"\x13ListPrefixesRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"B\n" +
	"\x14ListPrefixesResponse\x12*\n" +
	"\bprefixes\x18\x01 \x03(\v2\x0e.api.v1.PrefixR\bprefixes\"Y\n" +
	"\x12PrefixUsageRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"\xf9\x01\n" +
	"\x13PrefixUsageResponse\x12#\n" +
	"\ravailable_ips\x18\x01 \x01(\x04R\favailableIps\x12!\n" +
	"\facquired_ips\x18\x02 \x01(\x04R\vacquiredIps\x12>\n" +
	"\x1bavailable_smallest_prefixes\x18\x03 \x01(\x04R\x19availableSmallestPrefixes\x12-\n" +
	"\x12available_prefixes\x18\x04 \x03(\tR\x11availablePrefixes\x12+\n" +
	"\x11acquired_prefixes\x18\x05 \x01(\x04R\x10acquiredPrefixes\"\xab\x01\n" +
	"\x19AcquireChildPrefixRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\x12\"\n" +
	"\n" +
	"child_cidr\x18\x03 \x01(\tH\x00R\tchildCidr\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x04 \x01(\tH\x01R\tnamespace\x88\x01\x01B\r\n" +
	"\v_child_cidrB\f\n" +
	"\n" +
	"_namespace\"`\n" +
	"\x19ReleaseChildPrefixRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"9\n" +
	"\x02IP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12#\n" +
	"\rparent_prefix\x18\x02 \x01(\tR\fparentPrefix\"`\n" +
	"\x11AcquireIPResponse\x12\x1a\n" +
	"\x02ip\x18\x01 \x01(\v2\n" +
	".api.v1.IPR\x02ip\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"/\n" +
	"\x11ReleaseIPResponse\x12\x1a\n" +
	"\x02ip\x18\x01 \x01(\v2\n" +
	".api.v1.IPR\x02ip\"\x80\x01\n" +
	"\x10AcquireIPRequest\x12\x1f\n" +
	"\vprefix_cidr\x18\x01 \x01(\tR\n" +
	"prefixCidr\x12\x13\n" +
	"\x02ip\x18\x02 \x01(\tH\x00R\x02ip\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x01R\tnamespace\x88\x01\x01B\x05\n" +
	"\x03_ipB\f\n" +
	"\n" +
	"_namespace\"t\n" +
	"\x10ReleaseIPRequest\x12\x1f\n" +
	"\vprefix_cidr\x18\x01 \x01(\tR\n" +
	"prefixCidr\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\">\n" +
	"\vDumpRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"\"\n" +
	"\fDumpResponse\x12\x12\n" +
	"\x04dump\x18\x01 \x01(\tR\x04dump\"R\n" +
	"\vLoadRequest\x12\x12\n" +
	"\x04dump\x18\x01 \x01(\tR\x04dump\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"\x0e\n" +
	"\fLoadResponse\"6\n" +
	"\x16CreateNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x19\n" +
	"\x17CreateNamespaceResponse\"\x17\n" +
	"\x15ListNamespacesRequest\"6\n" +
	"\x16ListNamespacesResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x03(\tR\tnamespace\"6\n" +
	"\x16DeleteNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x19\n" +
	"\x17DeleteNamespaceResponse\"\x10\n" +
	"\x0eVersionRequest\"\x81\x01\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x19\n" +
	"\bgit_sha1\x18\x03 \x01(\tR\agitSha1\x12\x1d\n" +
	"\n" +
	"build_date\x18\x04 \x01(\tR\tbuildDate2\xd1\b\n" +
	"\vIpamService\x12I\n" +
	"\fCreatePrefix\x12\x1b.api.v1.CreatePrefixRequest\x1a\x1c.api.v1.CreatePrefixResponse\x12I\n" +
	"\fDeletePrefix\x12\x1b.api.v1.DeletePrefixRequest\x1a\x1c.api.v1.DeletePrefixResponse\x12@\n" +
	"\tGetPrefix\x12\x18.api.v1.GetPrefixRequest\x1a\x19.api.v1.GetPrefixResponse\x12I\n" +
	"\fListPrefixes\x12\x1b.api.v1.ListPrefixesRequest\x1a\x1c.api.v1.ListPrefixesResponse\x12F\n" +
	"\vPrefixUsage\x12\x1a.api.v1.PrefixUsageRequest\x1a\x1b.api.v1.PrefixUsageResponse\x12[\n" +
	"\x12AcquireChildPrefix\x12!.api.v1.AcquireChildPrefixRequest\x1a\".api.v1.AcquireChildPrefixResponse\x12[\n" +
	"\x12ReleaseChildPrefix\x12!.api.v1.ReleaseChildPrefixRequest\x1a\".api.v1.ReleaseChildPrefixResponse\x12@\n" +
	"\tAcquireIP\x12\x18.api.v1.AcquireIPRequest\x1a\x19.api.v1.AcquireIPResponse\x12@\n" +
	"\tReleaseIP\x12\x18.api.v1.ReleaseIPRequest\x1a\x19.api.v1.ReleaseIPResponse\x121\n" +
	"\x04Dump\x12\x13.api.v1.DumpRequest\x1a\x14.api.v1.DumpResponse\x121\n" +
	"\x04Load\x12\x13.api.v1.LoadRequest\x1a\x14.api.v1.LoadResponse\x12R\n" +
	"\x0fCreateNamespace\x12\x1e.api.v1.CreateNamespaceRequest\x1a\x1f.api.v1.CreateNamespaceResponse\x12O\n" +
	"\x0eListNamespaces\x12\x1d.api.v1.ListNamespacesRequest\x1a\x1e.api.v1.ListNamespacesResponse\x12R\n" +
	"\x0fDeleteNamespace\x12\x1e.api.v1.DeleteNamespaceRequest\x1a\x1f.api.v1.DeleteNamespaceResponse\x12:\n" +
	"\aVersion\x12\x16.api.v1.VersionRequest\x1a\x17.api.v1.VersionResponseB}\n" +
	"\n" +
	"com.api.v1B\tIpamProtoP\x01Z+github.com/metal-stack/go-ipam/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_ipam_proto_rawDescOnce sync.Once
	file_api_v1_ipam_proto_rawDescData []byte
)

func file_api_v1_ipam_proto_rawDescGZIP() []byte {
	file_api_v1_ipam_proto_rawDescOnce.Do(func() {
		file_api_v1_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ipam_proto_rawDesc), len(file_api_v1_ipam_proto_rawDesc)))
	})
	return file_api_v1_ipam_proto_rawDescData
}

var file_api_v1_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_v1_ipam_proto_goTypes = []any{
	(*Prefix)(nil),                     // 0: api.v1.Prefix
	(*CreatePrefixResponse)(nil),       // 1: api.v1.CreatePrefixResponse
	(*DeletePrefixResponse)(nil),       // 2: api.v1.DeletePrefixResponse
	(*GetPrefixResponse)(nil),          // 3: api.v1.GetPrefixResponse
	(*AcquireChildPrefixResponse)(nil), // 4: api.v1.AcquireChildPrefixResponse
	(*ReleaseChildPrefixResponse)(nil), // 5: api.v1.ReleaseChildPrefixResponse
	(*CreatePrefixRequest)(nil),        // 6: api.v1.CreatePrefixRequest
	(*DeletePrefixRequest)(nil),        // 7: api.v1.DeletePrefixRequest
	(*GetPrefixRequest)(nil),           // 8: api.v1.GetPrefixRequest
	(*ListPrefixesRequest)(nil),        // 9: api.v1.ListPrefixesRequest
	(*ListPrefixesResponse)(nil),       // 10: api.v1.ListPrefixesResponse
	(*PrefixUsageRequest)(nil),         // 11: api.v1.PrefixUsageRequest
	(*PrefixUsageResponse)(nil),        // 12: api.v1.PrefixUsageResponse
	(*AcquireChildPrefixRequest)(nil),  // 13: api.v1.AcquireChildPrefixRequest
	(*ReleaseChildPrefixRequest)(nil),  // 14: api.v1.ReleaseChildPrefixRequest
	(*IP)(nil),                         // 15: api.v1.IP
	(*AcquireIPResponse)(nil),          // 16: api.v1.AcquireIPResponse
	(*ReleaseIPResponse)(nil),          // 17: api.v1.ReleaseIPResponse
	(*AcquireIPRequest)(nil),           // 18: api.v1.AcquireIPRequest
	(*ReleaseIPRequest)(nil),           // 19: api.v1.ReleaseIPRequest
	(*DumpRequest)(nil),                // 20: api.v1.DumpRequest
	(*DumpResponse)(nil),               // 21: api.v1.DumpResponse
	(*LoadRequest)(nil),                // 22: api.v1.LoadRequest
	(*LoadResponse)(nil),               // 23: api.v1.LoadResponse
	(*CreateNamespaceRequest)(nil),     // 24: api.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil),    // 25: api.v1.CreateNamespaceResponse
	(*ListNamespacesRequest)(nil),      // 26: api.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),     // 27: api.v1.ListNamespacesResponse
	(*DeleteNamespaceRequest)(nil),     // 28: api.v1.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil),    // 29: api.v1.DeleteNamespaceResponse
	(*VersionRequest)(nil),             // 30: api.v1.VersionRequest
	(*VersionResponse)(nil),            // 31: api.v1.VersionResponse
}
var file_api_v1_ipam_proto_depIdxs = []int32{
	0,  // 0: api.v1.CreatePrefixResponse.prefix:type_name -> api.v1.Prefix
	0,  // 1: api.v1.DeletePrefixResponse.prefix:type_name -> api.v1.Prefix
	0,  // 2: api.v1.GetPrefixResponse.prefix:type_name -> api.v1.Prefix
	0,  // 3: api.v1.AcquireChildPrefixResponse.prefix:type_name -> api.v1.Prefix
	0,  // 4: api.v1.ReleaseChildPrefixResponse.prefix:type_name -> api.v1.Prefix
	0,  // 5: api.v1.ListPrefixesResponse.prefixes:type_name -> api.v1.Prefix
	15, // 6: api.v1.AcquireIPResponse.ip:type_name -> api.v1.IP
	15, // 7: api.v1.ReleaseIPResponse.ip:type_name -> api.v1.IP
	6,  // 8: api.v1.IpamService.CreatePrefix:input_type -> api.v1.CreatePrefixRequest
	7,  // 9: api.v1.IpamService.DeletePrefix:input_type -> api.v1.DeletePrefixRequest
	8,  // 10: api.v1.IpamService.GetPrefix:input_type -> api.v1.GetPrefixRequest
	9,  // 11: api.v1.IpamService.ListPrefixes:input_type -> api.v1.ListPrefixesRequest
	11, // 12: api.v1.IpamService.PrefixUsage:input_type -> api.v1.PrefixUsageRequest
	13, // 13: api.v1.IpamService.AcquireChildPrefix:input_type -> api.v1.AcquireChildPrefixRequest
	14, // 14: api.v1.IpamService.ReleaseChildPrefix:input_type -> api.v1.ReleaseChildPrefixRequest
	18, // 15: api.v1.IpamService.AcquireIP:input_type -> api.v1.AcquireIPRequest
	19, // 16: api.v1.IpamService.ReleaseIP:input_type -> api.v1.ReleaseIPRequest
	20, // 17: api.v1.IpamService.Dump:input_type -> api.v1.DumpRequest
	22, // 18: api.v1.IpamService.Load:input_type -> api.v1.LoadRequest
	24, // 19: api.v1.IpamService.CreateNamespace:input_type -> api.v1.CreateNamespaceRequest
	26, // 20: api.v1.IpamService.ListNamespaces:input_type -> api.v1.ListNamespacesRequest
	28, // 21: api.v1.IpamService.DeleteNamespace:input_type -> api.v1.DeleteNamespaceRequest
	30, // 22: api.v1.IpamService.Version:input_type -> api.v1.VersionRequest
	1,  // 23: api.v1.IpamService.CreatePrefix:output_type -> api.v1.CreatePrefixResponse
	2,  // 24: api.v1.IpamService.DeletePrefix:output_type -> api.v1.DeletePrefixResponse
	3,  // 25: api.v1.IpamService.GetPrefix:output_type -> api.v1.GetPrefixResponse
	10, // 26: api.v1.IpamService.ListPrefixes:output_type -> api.v1.ListPrefixesResponse
	12, // 27: api.v1.IpamService.PrefixUsage:output_type -> api.v1.PrefixUsageResponse
	4,  // 28: api.v1.IpamService.AcquireChildPrefix:output_type -> api.v1.AcquireChildPrefixResponse
	5,  // 29: api.v1.IpamService.ReleaseChildPrefix:output_type -> api.v1.ReleaseChildPrefixResponse
	16, // 30: api.v1.IpamService.AcquireIP:output_type -> api.v1.AcquireIPResponse
	17, // 31: api.v1.IpamService.ReleaseIP:output_type -> api.v1.ReleaseIPResponse
	21, // 32: api.v1.IpamService.Dump:output_type -> api.v1.DumpResponse
	23, // 33: api.v1.IpamService.Load:output_type -> api.v1.LoadResponse
	25, // 34: api.v1.IpamService.CreateNamespace:output_type -> api.v1.CreateNamespaceResponse
	27, // 35: api.v1.IpamService.ListNamespaces:output_type -> api.v1.ListNamespacesResponse
	29, // 36: api.v1.IpamService.DeleteNamespace:output_type -> api.v1.DeleteNamespaceResponse
	31, // 37: api.v1.IpamService.Version:output_type -> api.v1.VersionResponse
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_ipam_proto_init() }
func file_api_v1_ipam_proto_init() {
	if File_api_v1_ipam_proto != nil {
		return
	}
	file_api_v1_ipam_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[20].OneofWrappers = []any{}
	file_api_v1_ipam_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ipam_proto_rawDesc), len(file_api_v1_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ipam_proto_goTypes,
		DependencyIndexes: file_api_v1_ipam_proto_depIdxs,
		MessageInfos:      file_api_v1_ipam_proto_msgTypes,
	}.Build()
	File_api_v1_ipam_proto = out.File
	file_api_v1_ipam_proto_goTypes = nil
	file_api_v1_ipam_proto_depIdxs = nil
}
