// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/ipam.proto

package apiv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/metal-stack/go-ipam/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// IpamServiceName is the fully-qualified name of the IpamService service.
	IpamServiceName = "api.v1.IpamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IpamServiceCreatePrefixProcedure is the fully-qualified name of the IpamService's CreatePrefix
	// RPC.
	IpamServiceCreatePrefixProcedure = "/api.v1.IpamService/CreatePrefix"
	// IpamServiceDeletePrefixProcedure is the fully-qualified name of the IpamService's DeletePrefix
	// RPC.
	IpamServiceDeletePrefixProcedure = "/api.v1.IpamService/DeletePrefix"
	// IpamServiceGetPrefixProcedure is the fully-qualified name of the IpamService's GetPrefix RPC.
	IpamServiceGetPrefixProcedure = "/api.v1.IpamService/GetPrefix"
	// IpamServiceListPrefixesProcedure is the fully-qualified name of the IpamService's ListPrefixes
	// RPC.
	IpamServiceListPrefixesProcedure = "/api.v1.IpamService/ListPrefixes"
	// IpamServicePrefixUsageProcedure is the fully-qualified name of the IpamService's PrefixUsage RPC.
	IpamServicePrefixUsageProcedure = "/api.v1.IpamService/PrefixUsage"
	// IpamServiceAcquireChildPrefixProcedure is the fully-qualified name of the IpamService's
	// AcquireChildPrefix RPC.
	IpamServiceAcquireChildPrefixProcedure = "/api.v1.IpamService/AcquireChildPrefix"
	// IpamServiceReleaseChildPrefixProcedure is the fully-qualified name of the IpamService's
	// ReleaseChildPrefix RPC.
	IpamServiceReleaseChildPrefixProcedure = "/api.v1.IpamService/ReleaseChildPrefix"
	// IpamServiceAcquireIPProcedure is the fully-qualified name of the IpamService's AcquireIP RPC.
	IpamServiceAcquireIPProcedure = "/api.v1.IpamService/AcquireIP"
	// IpamServiceReleaseIPProcedure is the fully-qualified name of the IpamService's ReleaseIP RPC.
	IpamServiceReleaseIPProcedure = "/api.v1.IpamService/ReleaseIP"
	// IpamServiceDumpProcedure is the fully-qualified name of the IpamService's Dump RPC.
	IpamServiceDumpProcedure = "/api.v1.IpamService/Dump"
	// IpamServiceLoadProcedure is the fully-qualified name of the IpamService's Load RPC.
	IpamServiceLoadProcedure = "/api.v1.IpamService/Load"
	// IpamServiceCreateNamespaceProcedure is the fully-qualified name of the IpamService's
	// CreateNamespace RPC.
	IpamServiceCreateNamespaceProcedure = "/api.v1.IpamService/CreateNamespace"
	// IpamServiceListNamespacesProcedure is the fully-qualified name of the IpamService's
	// ListNamespaces RPC.
	IpamServiceListNamespacesProcedure = "/api.v1.IpamService/ListNamespaces"
	// IpamServiceDeleteNamespaceProcedure is the fully-qualified name of the IpamService's
	// DeleteNamespace RPC.
	IpamServiceDeleteNamespaceProcedure = "/api.v1.IpamService/DeleteNamespace"
)

// IpamServiceClient is a client for the api.v1.IpamService service.
type IpamServiceClient interface {
	CreatePrefix(context.Context, *connect_go.Request[v1.CreatePrefixRequest]) (*connect_go.Response[v1.CreatePrefixResponse], error)
	DeletePrefix(context.Context, *connect_go.Request[v1.DeletePrefixRequest]) (*connect_go.Response[v1.DeletePrefixResponse], error)
	GetPrefix(context.Context, *connect_go.Request[v1.GetPrefixRequest]) (*connect_go.Response[v1.GetPrefixResponse], error)
	ListPrefixes(context.Context, *connect_go.Request[v1.ListPrefixesRequest]) (*connect_go.Response[v1.ListPrefixesResponse], error)
	PrefixUsage(context.Context, *connect_go.Request[v1.PrefixUsageRequest]) (*connect_go.Response[v1.PrefixUsageResponse], error)
	AcquireChildPrefix(context.Context, *connect_go.Request[v1.AcquireChildPrefixRequest]) (*connect_go.Response[v1.AcquireChildPrefixResponse], error)
	ReleaseChildPrefix(context.Context, *connect_go.Request[v1.ReleaseChildPrefixRequest]) (*connect_go.Response[v1.ReleaseChildPrefixResponse], error)
	AcquireIP(context.Context, *connect_go.Request[v1.AcquireIPRequest]) (*connect_go.Response[v1.AcquireIPResponse], error)
	ReleaseIP(context.Context, *connect_go.Request[v1.ReleaseIPRequest]) (*connect_go.Response[v1.ReleaseIPResponse], error)
	Dump(context.Context, *connect_go.Request[v1.DumpRequest]) (*connect_go.Response[v1.DumpResponse], error)
	Load(context.Context, *connect_go.Request[v1.LoadRequest]) (*connect_go.Response[v1.LoadResponse], error)
	CreateNamespace(context.Context, *connect_go.Request[v1.CreateNamespaceRequest]) (*connect_go.Response[v1.CreateNamespaceResponse], error)
	ListNamespaces(context.Context, *connect_go.Request[v1.ListNamespacesRequest]) (*connect_go.Response[v1.ListNamespacesResponse], error)
	DeleteNamespace(context.Context, *connect_go.Request[v1.DeleteNamespaceRequest]) (*connect_go.Response[v1.DeleteNamespaceResponse], error)
}

// NewIpamServiceClient constructs a client for the api.v1.IpamService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIpamServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) IpamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &ipamServiceClient{
		createPrefix: connect_go.NewClient[v1.CreatePrefixRequest, v1.CreatePrefixResponse](
			httpClient,
			baseURL+IpamServiceCreatePrefixProcedure,
			opts...,
		),
		deletePrefix: connect_go.NewClient[v1.DeletePrefixRequest, v1.DeletePrefixResponse](
			httpClient,
			baseURL+IpamServiceDeletePrefixProcedure,
			opts...,
		),
		getPrefix: connect_go.NewClient[v1.GetPrefixRequest, v1.GetPrefixResponse](
			httpClient,
			baseURL+IpamServiceGetPrefixProcedure,
			opts...,
		),
		listPrefixes: connect_go.NewClient[v1.ListPrefixesRequest, v1.ListPrefixesResponse](
			httpClient,
			baseURL+IpamServiceListPrefixesProcedure,
			opts...,
		),
		prefixUsage: connect_go.NewClient[v1.PrefixUsageRequest, v1.PrefixUsageResponse](
			httpClient,
			baseURL+IpamServicePrefixUsageProcedure,
			opts...,
		),
		acquireChildPrefix: connect_go.NewClient[v1.AcquireChildPrefixRequest, v1.AcquireChildPrefixResponse](
			httpClient,
			baseURL+IpamServiceAcquireChildPrefixProcedure,
			opts...,
		),
		releaseChildPrefix: connect_go.NewClient[v1.ReleaseChildPrefixRequest, v1.ReleaseChildPrefixResponse](
			httpClient,
			baseURL+IpamServiceReleaseChildPrefixProcedure,
			opts...,
		),
		acquireIP: connect_go.NewClient[v1.AcquireIPRequest, v1.AcquireIPResponse](
			httpClient,
			baseURL+IpamServiceAcquireIPProcedure,
			opts...,
		),
		releaseIP: connect_go.NewClient[v1.ReleaseIPRequest, v1.ReleaseIPResponse](
			httpClient,
			baseURL+IpamServiceReleaseIPProcedure,
			opts...,
		),
		dump: connect_go.NewClient[v1.DumpRequest, v1.DumpResponse](
			httpClient,
			baseURL+IpamServiceDumpProcedure,
			opts...,
		),
		load: connect_go.NewClient[v1.LoadRequest, v1.LoadResponse](
			httpClient,
			baseURL+IpamServiceLoadProcedure,
			opts...,
		),
		createNamespace: connect_go.NewClient[v1.CreateNamespaceRequest, v1.CreateNamespaceResponse](
			httpClient,
			baseURL+IpamServiceCreateNamespaceProcedure,
			opts...,
		),
		listNamespaces: connect_go.NewClient[v1.ListNamespacesRequest, v1.ListNamespacesResponse](
			httpClient,
			baseURL+IpamServiceListNamespacesProcedure,
			opts...,
		),
		deleteNamespace: connect_go.NewClient[v1.DeleteNamespaceRequest, v1.DeleteNamespaceResponse](
			httpClient,
			baseURL+IpamServiceDeleteNamespaceProcedure,
			opts...,
		),
	}
}

// ipamServiceClient implements IpamServiceClient.
type ipamServiceClient struct {
	createPrefix       *connect_go.Client[v1.CreatePrefixRequest, v1.CreatePrefixResponse]
	deletePrefix       *connect_go.Client[v1.DeletePrefixRequest, v1.DeletePrefixResponse]
	getPrefix          *connect_go.Client[v1.GetPrefixRequest, v1.GetPrefixResponse]
	listPrefixes       *connect_go.Client[v1.ListPrefixesRequest, v1.ListPrefixesResponse]
	prefixUsage        *connect_go.Client[v1.PrefixUsageRequest, v1.PrefixUsageResponse]
	acquireChildPrefix *connect_go.Client[v1.AcquireChildPrefixRequest, v1.AcquireChildPrefixResponse]
	releaseChildPrefix *connect_go.Client[v1.ReleaseChildPrefixRequest, v1.ReleaseChildPrefixResponse]
	acquireIP          *connect_go.Client[v1.AcquireIPRequest, v1.AcquireIPResponse]
	releaseIP          *connect_go.Client[v1.ReleaseIPRequest, v1.ReleaseIPResponse]
	dump               *connect_go.Client[v1.DumpRequest, v1.DumpResponse]
	load               *connect_go.Client[v1.LoadRequest, v1.LoadResponse]
	createNamespace    *connect_go.Client[v1.CreateNamespaceRequest, v1.CreateNamespaceResponse]
	listNamespaces     *connect_go.Client[v1.ListNamespacesRequest, v1.ListNamespacesResponse]
	deleteNamespace    *connect_go.Client[v1.DeleteNamespaceRequest, v1.DeleteNamespaceResponse]
}

// CreatePrefix calls api.v1.IpamService.CreatePrefix.
func (c *ipamServiceClient) CreatePrefix(ctx context.Context, req *connect_go.Request[v1.CreatePrefixRequest]) (*connect_go.Response[v1.CreatePrefixResponse], error) {
	return c.createPrefix.CallUnary(ctx, req)
}

// DeletePrefix calls api.v1.IpamService.DeletePrefix.
func (c *ipamServiceClient) DeletePrefix(ctx context.Context, req *connect_go.Request[v1.DeletePrefixRequest]) (*connect_go.Response[v1.DeletePrefixResponse], error) {
	return c.deletePrefix.CallUnary(ctx, req)
}

// GetPrefix calls api.v1.IpamService.GetPrefix.
func (c *ipamServiceClient) GetPrefix(ctx context.Context, req *connect_go.Request[v1.GetPrefixRequest]) (*connect_go.Response[v1.GetPrefixResponse], error) {
	return c.getPrefix.CallUnary(ctx, req)
}

// ListPrefixes calls api.v1.IpamService.ListPrefixes.
func (c *ipamServiceClient) ListPrefixes(ctx context.Context, req *connect_go.Request[v1.ListPrefixesRequest]) (*connect_go.Response[v1.ListPrefixesResponse], error) {
	return c.listPrefixes.CallUnary(ctx, req)
}

// PrefixUsage calls api.v1.IpamService.PrefixUsage.
func (c *ipamServiceClient) PrefixUsage(ctx context.Context, req *connect_go.Request[v1.PrefixUsageRequest]) (*connect_go.Response[v1.PrefixUsageResponse], error) {
	return c.prefixUsage.CallUnary(ctx, req)
}

// AcquireChildPrefix calls api.v1.IpamService.AcquireChildPrefix.
func (c *ipamServiceClient) AcquireChildPrefix(ctx context.Context, req *connect_go.Request[v1.AcquireChildPrefixRequest]) (*connect_go.Response[v1.AcquireChildPrefixResponse], error) {
	return c.acquireChildPrefix.CallUnary(ctx, req)
}

// ReleaseChildPrefix calls api.v1.IpamService.ReleaseChildPrefix.
func (c *ipamServiceClient) ReleaseChildPrefix(ctx context.Context, req *connect_go.Request[v1.ReleaseChildPrefixRequest]) (*connect_go.Response[v1.ReleaseChildPrefixResponse], error) {
	return c.releaseChildPrefix.CallUnary(ctx, req)
}

// AcquireIP calls api.v1.IpamService.AcquireIP.
func (c *ipamServiceClient) AcquireIP(ctx context.Context, req *connect_go.Request[v1.AcquireIPRequest]) (*connect_go.Response[v1.AcquireIPResponse], error) {
	return c.acquireIP.CallUnary(ctx, req)
}

// ReleaseIP calls api.v1.IpamService.ReleaseIP.
func (c *ipamServiceClient) ReleaseIP(ctx context.Context, req *connect_go.Request[v1.ReleaseIPRequest]) (*connect_go.Response[v1.ReleaseIPResponse], error) {
	return c.releaseIP.CallUnary(ctx, req)
}

// Dump calls api.v1.IpamService.Dump.
func (c *ipamServiceClient) Dump(ctx context.Context, req *connect_go.Request[v1.DumpRequest]) (*connect_go.Response[v1.DumpResponse], error) {
	return c.dump.CallUnary(ctx, req)
}

// Load calls api.v1.IpamService.Load.
func (c *ipamServiceClient) Load(ctx context.Context, req *connect_go.Request[v1.LoadRequest]) (*connect_go.Response[v1.LoadResponse], error) {
	return c.load.CallUnary(ctx, req)
}

// CreateNamespace calls api.v1.IpamService.CreateNamespace.
func (c *ipamServiceClient) CreateNamespace(ctx context.Context, req *connect_go.Request[v1.CreateNamespaceRequest]) (*connect_go.Response[v1.CreateNamespaceResponse], error) {
	return c.createNamespace.CallUnary(ctx, req)
}

// ListNamespaces calls api.v1.IpamService.ListNamespaces.
func (c *ipamServiceClient) ListNamespaces(ctx context.Context, req *connect_go.Request[v1.ListNamespacesRequest]) (*connect_go.Response[v1.ListNamespacesResponse], error) {
	return c.listNamespaces.CallUnary(ctx, req)
}

// DeleteNamespace calls api.v1.IpamService.DeleteNamespace.
func (c *ipamServiceClient) DeleteNamespace(ctx context.Context, req *connect_go.Request[v1.DeleteNamespaceRequest]) (*connect_go.Response[v1.DeleteNamespaceResponse], error) {
	return c.deleteNamespace.CallUnary(ctx, req)
}

// IpamServiceHandler is an implementation of the api.v1.IpamService service.
type IpamServiceHandler interface {
	CreatePrefix(context.Context, *connect_go.Request[v1.CreatePrefixRequest]) (*connect_go.Response[v1.CreatePrefixResponse], error)
	DeletePrefix(context.Context, *connect_go.Request[v1.DeletePrefixRequest]) (*connect_go.Response[v1.DeletePrefixResponse], error)
	GetPrefix(context.Context, *connect_go.Request[v1.GetPrefixRequest]) (*connect_go.Response[v1.GetPrefixResponse], error)
	ListPrefixes(context.Context, *connect_go.Request[v1.ListPrefixesRequest]) (*connect_go.Response[v1.ListPrefixesResponse], error)
	PrefixUsage(context.Context, *connect_go.Request[v1.PrefixUsageRequest]) (*connect_go.Response[v1.PrefixUsageResponse], error)
	AcquireChildPrefix(context.Context, *connect_go.Request[v1.AcquireChildPrefixRequest]) (*connect_go.Response[v1.AcquireChildPrefixResponse], error)
	ReleaseChildPrefix(context.Context, *connect_go.Request[v1.ReleaseChildPrefixRequest]) (*connect_go.Response[v1.ReleaseChildPrefixResponse], error)
	AcquireIP(context.Context, *connect_go.Request[v1.AcquireIPRequest]) (*connect_go.Response[v1.AcquireIPResponse], error)
	ReleaseIP(context.Context, *connect_go.Request[v1.ReleaseIPRequest]) (*connect_go.Response[v1.ReleaseIPResponse], error)
	Dump(context.Context, *connect_go.Request[v1.DumpRequest]) (*connect_go.Response[v1.DumpResponse], error)
	Load(context.Context, *connect_go.Request[v1.LoadRequest]) (*connect_go.Response[v1.LoadResponse], error)
	CreateNamespace(context.Context, *connect_go.Request[v1.CreateNamespaceRequest]) (*connect_go.Response[v1.CreateNamespaceResponse], error)
	ListNamespaces(context.Context, *connect_go.Request[v1.ListNamespacesRequest]) (*connect_go.Response[v1.ListNamespacesResponse], error)
	DeleteNamespace(context.Context, *connect_go.Request[v1.DeleteNamespaceRequest]) (*connect_go.Response[v1.DeleteNamespaceResponse], error)
}

// NewIpamServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIpamServiceHandler(svc IpamServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(IpamServiceCreatePrefixProcedure, connect_go.NewUnaryHandler(
		IpamServiceCreatePrefixProcedure,
		svc.CreatePrefix,
		opts...,
	))
	mux.Handle(IpamServiceDeletePrefixProcedure, connect_go.NewUnaryHandler(
		IpamServiceDeletePrefixProcedure,
		svc.DeletePrefix,
		opts...,
	))
	mux.Handle(IpamServiceGetPrefixProcedure, connect_go.NewUnaryHandler(
		IpamServiceGetPrefixProcedure,
		svc.GetPrefix,
		opts...,
	))
	mux.Handle(IpamServiceListPrefixesProcedure, connect_go.NewUnaryHandler(
		IpamServiceListPrefixesProcedure,
		svc.ListPrefixes,
		opts...,
	))
	mux.Handle(IpamServicePrefixUsageProcedure, connect_go.NewUnaryHandler(
		IpamServicePrefixUsageProcedure,
		svc.PrefixUsage,
		opts...,
	))
	mux.Handle(IpamServiceAcquireChildPrefixProcedure, connect_go.NewUnaryHandler(
		IpamServiceAcquireChildPrefixProcedure,
		svc.AcquireChildPrefix,
		opts...,
	))
	mux.Handle(IpamServiceReleaseChildPrefixProcedure, connect_go.NewUnaryHandler(
		IpamServiceReleaseChildPrefixProcedure,
		svc.ReleaseChildPrefix,
		opts...,
	))
	mux.Handle(IpamServiceAcquireIPProcedure, connect_go.NewUnaryHandler(
		IpamServiceAcquireIPProcedure,
		svc.AcquireIP,
		opts...,
	))
	mux.Handle(IpamServiceReleaseIPProcedure, connect_go.NewUnaryHandler(
		IpamServiceReleaseIPProcedure,
		svc.ReleaseIP,
		opts...,
	))
	mux.Handle(IpamServiceDumpProcedure, connect_go.NewUnaryHandler(
		IpamServiceDumpProcedure,
		svc.Dump,
		opts...,
	))
	mux.Handle(IpamServiceLoadProcedure, connect_go.NewUnaryHandler(
		IpamServiceLoadProcedure,
		svc.Load,
		opts...,
	))
	mux.Handle(IpamServiceCreateNamespaceProcedure, connect_go.NewUnaryHandler(
		IpamServiceCreateNamespaceProcedure,
		svc.CreateNamespace,
		opts...,
	))
	mux.Handle(IpamServiceListNamespacesProcedure, connect_go.NewUnaryHandler(
		IpamServiceListNamespacesProcedure,
		svc.ListNamespaces,
		opts...,
	))
	mux.Handle(IpamServiceDeleteNamespaceProcedure, connect_go.NewUnaryHandler(
		IpamServiceDeleteNamespaceProcedure,
		svc.DeleteNamespace,
		opts...,
	))
	return "/api.v1.IpamService/", mux
}

// UnimplementedIpamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIpamServiceHandler struct{}

func (UnimplementedIpamServiceHandler) CreatePrefix(context.Context, *connect_go.Request[v1.CreatePrefixRequest]) (*connect_go.Response[v1.CreatePrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.CreatePrefix is not implemented"))
}

func (UnimplementedIpamServiceHandler) DeletePrefix(context.Context, *connect_go.Request[v1.DeletePrefixRequest]) (*connect_go.Response[v1.DeletePrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.DeletePrefix is not implemented"))
}

func (UnimplementedIpamServiceHandler) GetPrefix(context.Context, *connect_go.Request[v1.GetPrefixRequest]) (*connect_go.Response[v1.GetPrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.GetPrefix is not implemented"))
}

func (UnimplementedIpamServiceHandler) ListPrefixes(context.Context, *connect_go.Request[v1.ListPrefixesRequest]) (*connect_go.Response[v1.ListPrefixesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.ListPrefixes is not implemented"))
}

func (UnimplementedIpamServiceHandler) PrefixUsage(context.Context, *connect_go.Request[v1.PrefixUsageRequest]) (*connect_go.Response[v1.PrefixUsageResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.PrefixUsage is not implemented"))
}

func (UnimplementedIpamServiceHandler) AcquireChildPrefix(context.Context, *connect_go.Request[v1.AcquireChildPrefixRequest]) (*connect_go.Response[v1.AcquireChildPrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.AcquireChildPrefix is not implemented"))
}

func (UnimplementedIpamServiceHandler) ReleaseChildPrefix(context.Context, *connect_go.Request[v1.ReleaseChildPrefixRequest]) (*connect_go.Response[v1.ReleaseChildPrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.ReleaseChildPrefix is not implemented"))
}

func (UnimplementedIpamServiceHandler) AcquireIP(context.Context, *connect_go.Request[v1.AcquireIPRequest]) (*connect_go.Response[v1.AcquireIPResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.AcquireIP is not implemented"))
}

func (UnimplementedIpamServiceHandler) ReleaseIP(context.Context, *connect_go.Request[v1.ReleaseIPRequest]) (*connect_go.Response[v1.ReleaseIPResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.ReleaseIP is not implemented"))
}

func (UnimplementedIpamServiceHandler) Dump(context.Context, *connect_go.Request[v1.DumpRequest]) (*connect_go.Response[v1.DumpResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.Dump is not implemented"))
}

func (UnimplementedIpamServiceHandler) Load(context.Context, *connect_go.Request[v1.LoadRequest]) (*connect_go.Response[v1.LoadResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.Load is not implemented"))
}

func (UnimplementedIpamServiceHandler) CreateNamespace(context.Context, *connect_go.Request[v1.CreateNamespaceRequest]) (*connect_go.Response[v1.CreateNamespaceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.CreateNamespace is not implemented"))
}

func (UnimplementedIpamServiceHandler) ListNamespaces(context.Context, *connect_go.Request[v1.ListNamespacesRequest]) (*connect_go.Response[v1.ListNamespacesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.ListNamespaces is not implemented"))
}

func (UnimplementedIpamServiceHandler) DeleteNamespace(context.Context, *connect_go.Request[v1.DeleteNamespaceRequest]) (*connect_go.Response[v1.DeleteNamespaceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.IpamService.DeleteNamespace is not implemented"))
}
